# Generated by Django 3.0.4 on 2020-05-06 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.PositiveIntegerField(help_text='Use the following format: YYYY', null=True, validators=[django.core.validators.MaxValueValidator(2020)]),
        ),
        migrations.AlterField(
            model_name='author',
            name='dead_day',
            field=models.PositiveIntegerField(help_text='Use the following format: YYYY', null=True, validators=[django.core.validators.MaxValueValidator(2020)]),
        ),
        migrations.AlterField(
            model_name='painting',
            name='year',
            field=models.PositiveIntegerField(help_text='Use the following format: YYYY', validators=[django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
