# Generated by Django 3.0.3 on 2020-02-26 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('nickname', models.CharField(max_length=250, unique=True)),
                ('avatar', models.ImageField(default='default.png', upload_to='')),
                ('win_rate', models.FloatField(default=0)),
                ('games_total', models.PositiveIntegerField(default=0)),
                ('wins_total', models.PositiveIntegerField(default=0)),
                ('pictures_seen', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
