# Generated by Django 3.0.3 on 2020-03-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200227_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='pictures_seen',
        ),
    ]
