# Generated by Django 3.0.4 on 2020-03-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_progress_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='reached',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='win_rate',
        ),
        migrations.AddField(
            model_name='achievement',
            name='type',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
