export const SET_PAINTING = "SET_PAINTING";
export const SET_PAINTING_FAIL = "SET_PAINTING_FAIL";

export const SUBMIT_CORRECT_ANSWER = "SUBMIT_CORRECT_ANSWER";
export const SUBMIT_INCORRECT_ANSWER = "SUBMIT_INCORRECT_ANSWER";

export const SET_CORRECT_ANSWER = "SET_CORRECT_ANSWER";
export const SET_ANSWERS = "SET_ANSWERS";
export const SET_ANSWERED = "SET_ANSWERED";
export const SET_WINS_COUNTER = "SET_WINS_COUNTER";

export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";

export const SIGN_OUT = "SIGN_OUT";

export const GET_PAINTINGS = "GET_PAINTINGS";
export const GET_PAINTINGS_SUCCESS = "GET_PAINTINGS_SUCCESS";
export const GET_PAINTINGS_FAILURE = "GET_PAINTINGS_FAILURE";

export const UPDATE_PAINTING = "UPDATE_PAINTING";
export const UPDATE_PAINTING_SUCCESS = "UPDATE_PAINTING_SUCCESS";
export const UPDATE_PAINTING_FAILURE = "UPDATE_PAINTING_FAILURE";

export const GET_AUTHORS = "GET_AUTHORS";
export const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS";
export const GET_AUTHORS_FAILURE = "GET_AUTHORS_FAILURE";

export const GET_STYLES = "GET_STYLES";
export const GET_STYLES_SUCCESS = "GET_STYLES_SUCCESS";
export const GET_STYLES_FAILURE = "GET_STYLES_FAILURE";
