# Generated by Django 3.0.3 on 2020-02-10 17:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=200)),
                ('birth_date', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MaxValueValidator(2020)])),
                ('dead_day', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MaxValueValidator(2020)])),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('century', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MaxValueValidator(2020)])),
                ('gallery', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('author', models.ManyToManyField(to='quiz.Author')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Style')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Style'),
        ),
    ]
