# Generated by Django 3.0.3 on 2020-02-27 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='games_total',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pictures_seen',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='win_rate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wins_total',
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_rate', models.FloatField(default=0)),
                ('games_total', models.PositiveIntegerField(default=0)),
                ('wins_total', models.PositiveIntegerField(default=0)),
                ('pictures_seen', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
