# Generated by Django 3.0.4 on 2020-03-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200312_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
