# Generated by Django 3.0.4 on 2020-05-06 11:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_auto_20200506_1457'),
        ('user', '0010_auto_20200315_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(help_text='Use the following format: YYYY', validators=[django.core.validators.MaxValueValidator(2020)])),
                ('gallery', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='requests/')),
                ('status', models.IntegerField(choices=[(0, 'Rejected'), (1, 'Accepted'), (2, 'Edited and accepted'), (3, 'In progress')], default=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Author')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
